#if defined _snowy_whitelist_msgs_included // _snowy_whitelist_msgs_included
  #endinput
#endif
#define _snowy_whitelist_msgs_included

char g_joinMessage_Snowy[][] = {
    // Past (2025)
    "%s is here. Lock up your leashes and maybe your thighs.",
    "%s arrives with thigh highs, autism, and no apologies.",
    "%s has entered. Yes, she is autistic. Yes, she is wearing black. And yes, she is judging you.",
    "%s just entered. If anything's missing, check her tailhole.", // tailfluff.
    "%s arrived. A snow-white arctic fox with a criminal record", // (for stealing keyboards).",
    "Lock up your stuff. %s is here and she’s wearing black.",
    "%s padded in with silent steps and fluffy menace.",
    "%s has arrived. All systems: mildly concerned.",
    "%s just joined. Hope you weren’t using your spine.",
    "%s is in. The air got 3% gayer. And louder.",
    "%s is here. The vibes? Rotten. The hair? Glorious.",
    "%s has arrived. Probably gonna break someone. With love." // someone instead of something

    // 2026

}

// char g_joinMessage_[][] = {

// }